enum ERequestActions {
  CREATE_REQUEST_EQUIPMENT = "CREATE_REQUEST_EQUIPMENT",
  CREATE_REQUEST_EQUIPMENT_REQUEST = "CREATE_REQUEST_EQUIPMENT_REQUEST",
  CREATE_REQUEST_EQUIPMENT_SUCCESS = "CREATE_REQUEST_EQUIPMENT_SUCCESS",
  CREATE_REQUEST_EQUIPMENT_FAILURE = "CREATE_REQUEST_EQUIPMENT_FAILURE",

  GET_REQUEST_EQUIPMENT = "GET_REQUEST_EQUIPMENT",
  GET_REQUEST_EQUIPMENT_REQUEST = "GET_REQUEST_EQUIPMENT_REQUEST",
  GET_REQUEST_EQUIPMENT_SUCCESS = "GET_REQUEST_EQUIPMENT_SUCCESS",
  GET_REQUEST_EQUIPMENT_FAILURE = "GET_REQUEST_EQUIPMENT_FAILURE",

  CONFIRM_REQUEST_EQUIPMENT = "CONFIRM_REQUEST_EQUIPMENT",
  CONFIRM_REQUEST_EQUIPMENT_REQUEST = "CONFIRM_REQUEST_EQUIPMENT_REQUEST",
  CONFIRM_REQUEST_EQUIPMENT_SUCCESS = "CONFIRM_REQUEST_EQUIPMENT_SUCCESS",
  CONFIRM_REQUEST_EQUIPMENT_FAILURE = "CONFIRM_REQUEST_EQUIPMENT_FAILURE",

  REJECT_REQUEST_EQUIPMENT = "REJECT_REQUEST_EQUIPMENT",
  REJECT_REQUEST_EQUIPMENT_REQUEST = "REJECT_REQUEST_EQUIPMENT_REQUEST",
  REJECT_REQUEST_EQUIPMENT_SUCCESS = "REJECT_REQUEST_EQUIPMENT_SUCCESS",
  REJECT_REQUEST_EQUIPMENT_FAILURE = "REJECT_REQUEST_EQUIPMENT_FAILURE",

  DELETE_REQUEST_EQUIPMENT = "DELETE_REQUEST_EQUIPMENT",
  DELETE_REQUEST_EQUIPMENT_REQUEST = "DELETE_REQUEST_EQUIPMENT_REQUEST",
  DELETE_REQUEST_EQUIPMENT_SUCCESS = "DELETE_REQUEST_EQUIPMENT_SUCCESS",
  DELETE_REQUEST_EQUIPMENT_FAILURE = "DELETE_REQUEST_EQUIPMENT_FAILURE",
}

export { ERequestActions };
